### ISSUE TITLE
feature_encoding_layer

### ISSUE THREAD

**Issue by alfredtorres** [DylanWusee/pointconv#17]
Hi @DylanWusee 
Thank you for you excellent code. I'm implementing a Pytorch version on your work. 
I have a question about the feature_encoding_layer.
In your cvpr paper fig.5. The local feature F_in(KxC_in) will mutiply with the Density(KxC_in) directly.
But in your code,  the grouped_feature will conv before muliply with Density.
Am I right?
```
for i, num_out_channel in enumerate(mlp):
            if i != len(mlp) - 1:  
                grouped_feature = tf_util.conv2d(grouped_feature, num_out_channel, [1,1],  
                                            padding='VALID', stride=[1,1],  
                                            bn=bn, is_training=is_training,  
                                            scope='conv%d'%(i), bn_decay=bn_decay, weight_decay = weight_decay) 
weight = weight_net_hidden(grouped_xyz, [32], scope = 'weight_net', is_training=is_training, bn_decay = bn_decay, weight_decay = weight_decay)
density_scale = nonlinear_transform(density_scale, [16, 1], scope = 'density_net', is_training=is_training, bn_decay = bn_decay, weight_decay = weight_decay)
new_points = tf.multiply(grouped_feature, density_scale)
```
Cheers,
ziyu

**Comment by DylanWusee** [comment]
The MLP before the tf.multiply is just used to add nonlinearity in the network, which can be removed or set mlp=[]. 
The 1x1 conv in the fig.5 of the paper is this line:https://github.com/DylanWusee/pointconv/blob/21c1aac1e6cd00bc04cedbf368e53042157fc4ac/PointConv.py#L126
