### ISSUE TITLE
Modify evaluate_scannet.py to test

### ISSUE THREAD

**Issue by WenshuangSong** [DylanWusee/pointconv#31]
when I modify the  ply_path with 'scannetv2/scans_test' and the file_list = "./scannet/scannetv2_test.txt" and scannet_dataset_sw_rgb.ScannetDatasetWholeScene_evaluation(root=DATA_PATH, split='test', with_rgb = WITH_RGB),
there was something wrong happened.
Could you help  me? Thks! @DylanWusee 
![pointconvtest](https://user-images.githubusercontent.com/18051580/83351994-06e1fd00-a37b-11ea-871c-f33d7cbd98b6.png)

**Comment by DylanWusee** [comment]
I think that is a normal result since the ground truth of the test set is not publicly released. To evaluate the results, you need to upload to the ScanNet benchmark.

**Comment by WenshuangSong** [comment]
> I think that is a normal result since the ground truth of the test set is not publicly released. To evaluate the results, you need to upload to the ScanNet benchmark.

I know ! Thanks a lot !

**Comment by WenshuangSong** [comment]
> I think that is a normal result since the ground truth of the test set is not publicly released. To evaluate the results, you need to upload to the ScanNet benchmark.

Hi @DylanWusee ,thanks a lot for your reply!
Could you please release your test.py and predict.py to me ?
Cause I don't know how to modify the evaluate.py to test.py and predict.py.
Thanks a lot!
