### ISSUE TITLE
tf_interpolate_so.so

### ISSUE THREAD

**Issue by a14en9** [DylanWusee/pointconv#8]
Hi,

Thank you for sharing code.

I found a problem of "tf_interpolate_so.so" when I compile your source code. This is error message it throw out: "undefined symbol: _ZN10tensorflow15OpKernelContext10CtxFailureEPKciRKNS_6StatusE"

I couldn't figure out the problem, have you see this kind of error?

Thanks

**Comment by mzy97** [comment]
I have encounter the same problem, any ideas? thx

**Comment by heng94** [comment]
see https://github.com/charlesq34/pointnet2/issues/48#issuecomment-404482115 for the solution.
